### ISSUE TITLE
import pyproj from addon's directory?

### ISSUE THREAD

**Issue by vvoovv** [JeremyBYU/bpyproj#8]
Can pyproj be imported right from the bpyproj directory without moving it to site-packages?

The advantage is the correct addon removal: if the bpyproj is removed, pyproj is removed as well.

**Comment by JeremyBYU** [comment]
Hmm, yes I think it can *if* I hack the [path](https://stackoverflow.com/questions/7901373/configuring-python-to-use-additional-locations-for-site-packages). Your are correct that this is a better from the vantage point of removing pyproj when the add-on is removed, something I didn't think about.

It should be a quick fix! Thank you for all your help on this.

**Comment by vvoovv** [comment]
Just tried it. Seems to work (EPSG:3857)

Do we need to click "install dependencies" at all?
Could you just add the path to binaries right in __init__.py or in another appropriate module?

**Comment by JeremyBYU** [comment]
That's what I had originally done, have the plugin attempt to automatically install things. The problem was that if there was a problem it *felt* like the message came out of nowhere (just from starting up blender).  Also, before I was actually copying things so I thought it deserved and actual explicit step.

But now with your great idea of just modifying the system path, I think it makes sense to just attempt to do this on startup.  If we don't have the bundled dependency or an error I will just show the message.

**Comment by JeremyBYU** [comment]
Okay this should be done now.  Automatically tries to add to path from bundled package, if there's an issue it logs an error.
